- name: Ansible Deployments
  hosts: localhost #dev
  gather_facts: true
  become: false
  
  
  
  pre_tasks:
    - name: Create a Namespace
      kubernetes.core.k8s:
        kubeconfig: '~/.kube/config'
        api_version: v1
        kind: Namespace
        name: "ansible-testing"
        state: present
  
  
  
  tasks:
    - name: Deployment 1
      kubernetes.core.k8s:
         state: present
         definition:
           apiVersion: apps/v1
           kind: Deployment
           metadata:
             name: nodeapp-dep
             namespace: "ansible-testing"
             labels:
               app: nodeapp
           spec:
             replicas: 2
             revisionHistoryLimit: 20
             strategy:
               rollingUpdate:
                 maxSurge: 25%
                 maxUnavailable: 25%
               type: RollingUpdate
             selector:
               matchLabels:
                 app: nodeapp
                 tier: core
             template:
               metadata:
                 labels:
                   app: nodeapp
                   tier: core
               spec:
                 containers:
                   - name: nodeapp
                     image: hassanali70826/myapp:DOCKER_TAG
                     imagePullPolicy: Always    
                     ports:
                       - containerPort: 8080
                         name: nodeapp-p
                     resources:
                       limits:
                         cpu: 300m
                       requests:
                         cpu: 100m 
    - name: Service for Deployment 1 load balancer
      kubernetes.core.k8s:
       state: present
       definition:
        apiVersion: v1
        kind: Service
        metadata:
           name: nodeapp-dep-es
           namespace: "ansible-testing"
           labels:
             app: net
        spec:
          type: LoadBalancer
          selector:
              app: nodeapp
              tier: core
          ports:
          - port: 1105
            targetPort: 8080
            name: nodeapp-p
  post_tasks:
    - name: GET deployed micro-services for such name space "ansible-testing"
      shell: kubectl --kubeconfig=/home/{{ ansible_user_id }}/.kube/config -n ansible-testing get all
      register: results
      tags: get-info

    - debug: msg="{{ results.stdout.split('\n') }}"  

