---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: hassanali70826/myapp:DOCKER_TAG
        name: nodeapp
        ports:
        - containerPort: 8080
