---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: hassanali70826/myapp:DOCKER_TAG
        name: nodeapp
        ports:
          - containerPort: 8080
          name: mnp-hlr-port
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ansible-deployment-is
spec:
  selector:
    app: nodeapp
  type: clusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8080
    nodePort: 31110
